var buttonColors = ["red", "blue", "green", "yellow"];

var gamePattern = [];

var userClickedPattern = [];

var started = false;

var level = 1;

$(document).keydown(function (e) {
  if (!started) {
    nextSequence();
  }

  started = true;
});

$(".btn").click(function () {
  var userChosenColour = $(this).attr("id");
  userClickedPattern.push(userChosenColour);
  //playsound(userChosenColour);
  playSound(userChosenColour);
  animatePress(userChosenColour);

  checkAnswer(userClickedPattern.length - 1);
});

function playSound(name) {
  var audio = new Audio("sounds/" + name + ".mp3");
  audio.play();
}

function animatePress(currentcolor) {
  $("." + currentcolor).addClass("pressed");

  setTimeout(function () {
    $("." + currentcolor).removeClass("pressed");
  }, 100);
}

function startOver() {
  started = false;
  level = 1;
  gamePattern = [];
}

function checkAnswer(currentLevel) {
  // checks whether the userclicked button is same as the button generated by the nextseq method stored in gamePattern
  if (userClickedPattern[currentLevel] === gamePattern[currentLevel]) {
    console.log("Success");

    // checks if the length of the given pattern is equal to the game pattern or not
    if (userClickedPattern.length === gamePattern.length) {
      // if yes then the user has succesfully passed the level and next seq method is called to take game to level to and generate new gamepattren
      setTimeout(() => {
        nextSequence();
      }, 1000);
    }
  } else {
    console.log("Wrong");
    playSound("wrong");
    $("body").addClass("game-over");

    setTimeout(() => {
      $("body").removeClass("game-over");
    }, 200);

    $("h1").text("Game Over, Press Any Key to Restart");
    startOver();
  }
}

function nextSequence() {
  userClickedPattern = [];

  $("h1").text("Level " + level);

  var randomNumber = Math.floor(Math.random() * 4);

  var randomChooseColor = buttonColors[randomNumber];

  gamePattern.push(randomChooseColor);

  $("#" + randomChooseColor)
    .fadeIn(100)
    .fadeOut(100)
    .fadeIn(100);

  playSound(randomChooseColor);
  level = level + 1;
}
